### ISSUE TITLE
This error occurs when the bot receives a lot of message.

### ISSUE THREAD

**Issue by dongsu8142** [ansonfoong/Katana#10]
error: Uncaught TypeError: Cannot read property 'id' of undefined
  let user: User = client.users.get(author.id);
                                           ^
    at buildMessage (https://deno.land/x/katana/src/utils/resolvers.ts:252:44)
    at TextChannel.send (https://deno.land/x/katana/src/models/channels/TextChannel.ts:57:20)

**Comment by stuyy** [comment]
Yup. It's because you're getting rate limited from the Gateway, so it sends a Payload with an error message. Will have to handle this and apply some sort of rate limit.

**Comment by dongsu8142** [comment]
I hope this problem will be solved quickly and API will grow a lot.

**Comment by stuyy** [comment]
Yep, since the API allows 120 requests per 60 seconds, that means you can only send 2 events per second. So I might just add a setTimeout(). However, I may set up a PriorityQueue structure and use that to handle events to prevent rate limiting. Will have to experiment. Thank you for bringing this up.

**Comment by dongsu8142** [comment]
I want you to fix the error quickly.

**Comment by ITS-NIGHTOWL** [comment]
Stuff like this takes time, give the man a break

**Comment by dongsu8142** [comment]
okay I'm sorry I rushed you.
