### ISSUE TITLE
Issue with bot that's in a lot of servers.

### ISSUE THREAD

**Issue by Hexorshift** [ansonfoong/Katana#11]
My bot is in 44 servers and it serves around 16k members.

Here is the error:
```javascript
Download https://deno.land/x/katana/src/handlers/PRESENCE_UPDATE.ts
Download https://deno.land/x/katana/src/handlers/PRESENCE_UPDATE.ts
Download https://deno.land/x/katana/src/handlers/PRESENCE_UPDATE.ts
Download https://deno.land/x/katana/src/handlers/PRESENCE_UPDATE.ts
error: Uncaught TypeError: members is not iterable
  for (const member of members) {
                       ^
    at resolveGuildMembersAndUsers (https://deno.land/x/katana/src/utils/resolvers.ts:110:24)
    at default (https://deno.land/x/katana/src/handlers/READY.ts:40:23)
```

**Comment by ghost** [comment]
Well, what is `members` defined as? And did it work before, since you are assuming it's "an issue when it is in a lot of server"?

**Comment by Hexorshift** [comment]
> Well, what is `members` defined as? And did it work before, since you are assuming it's "an issue when it is in a lot of server"?

It's an error that is coming from the library itself.
